version: 2
cli:
    server: https://app.fossa.com
    fetcher: custom
    project: emperror.dev/errors
analyze:
    modules:
        -   name: emperror.dev/errors
            type: go
            target: emperror.dev/errors
            path: .
            options:
                allow-unresolved: true
