run:
    skip-dirs:
        - tests
    skip-files:
        - format_test.go
        - wrap_go1_12_test.go
        - wrap_test.go

linters:
    enable-all: true

linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: emperror.dev/errors
